# Generated by Django 4.2.12 on 2025-05-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0014_breed_slug_dog_slug_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='slug',
            field=models.SlugField(blank=True, default='temporary-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dog',
            name='slug',
            field=models.SlugField(blank=True, default='temporary-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
